apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django-backend
        image: mctoosh94/mynotes:backend-d53cc4872794ab4d14efbd978c18468f7c054ae0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret_key
        # Updated Database configuration from .env, using Secret and ConfigMap
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_HOST
          value: "postgres"  # Kubernetes service name for PostgreSQL -1
        - name: DB_PORT
          value: "5432"
