apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  type: NodePort
  selector:
    app: django-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
