apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  type: ClusterIP # This does not need to be external 
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: django-backend
