apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002  # This specifies the port on the node where the service can be accessed. Adjust if needed.
  selector:
    app: react-frontend
