apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: mctoosh94/mynotes:frontend-d53cc4872794ab4d14efbd978c18468f7c054ae0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
