name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - master 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Django Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile 
        push: true
        tags: mctoosh94/mynotes:backend-${{ github.sha }}

    - name: Build and Push React Image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile  
        push: true
        tags: mctoosh94/mynotes:frontend-${{ github.sha }}

    - name: Update Kubernetes Manifests with New Image Tags
      env:
        MY_PERSONAL_ACCESS_TOKEN: ${{ secrets.ARGOCD_NOTES_APP_PAT }}
      run: |
        sed -i 's|mctoosh94/mynotes:backend-latest|mctoosh94/mynotes:backend-${{ github.sha }}|' ./k8s/django-deployment.yaml
        sed -i 's|mctoosh94/mynotes:frontend-latest|mctoosh94/mynotes:frontend-${{ github.sha }}|' ./k8s/react-deployment.yaml
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add ./k8s/*.yaml
        git commit -m "Update Kubernetes manifests to new image tags"
        git remote set-url origin https://${{ secrets.ARGOCD_NOTES_APP_PAT }}:x-oauth-basic@github.com/Abukhalid22/Simple-Note-App.git
        git push origin HEAD:master
