name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DJANGO_IMAGE_TAG: mctoosh94/mynotes:backend-${{ github.sha }}
      REACT_IMAGE_TAG: mctoosh94/mynotes:frontend-${{ github.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Add this step to fetch the latest changes from the repository
      - name: Fetch latest changes
        run: git fetch --prune --unshallow

      - name: Build and Push Django Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DJANGO_IMAGE_TAG }}

      - name: Build and Push React Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.REACT_IMAGE_TAG }}

      - name: Update Kubernetes Manifests with New Image Tags
        env:
          MY_PERSONAL_ACCESS_TOKEN: ${{ secrets.ARGOCD_NOTES_APP_PAT }}
        run: |
          sed -i "s|image: ***/mynotes:backend-.*|image: ***/mynotes:backend-${{ github.sha }}|" ./k8s/django-deployment.yaml
          sed -i "s|image: ***/mynotes:frontend-.*|image: ***/mynotes:frontend-${{ github.sha }}|" ./k8s/react-deployment.yaml
          
          # Debug: Display the updated files for verification
          echo "Displaying updated django-deployment.yaml"
          cat ./k8s/django-deployment.yaml
          echo "Displaying updated react-deployment.yaml"
          cat ./k8s/react-deployment.yaml
          
          # Add modified files to the staging area
          git add ./k8s/*.yaml
          
          # Explicitly check for changes
          git diff --quiet
          if [ $? -ne 0 ]; then
            echo "Changes detected, updating Kubernetes manifests."
            git config user.name 'GitHub Actions'
            git config user.email 'actions@github.com'
            
            git commit -m "Update Kubernetes manifests to new image tags: ${{ github.sha }}"
            git push https://${{ secrets.ARGOCD_NOTES_APP_PAT }}:x-oauth-basic@github.com/Abukhalid22/Simple-Note-App.git HEAD:master
          else
            echo "No changes to Kubernetes manifests. Skipping commit and push."
          fi
